/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'philipp' at '27.04.16 20:41' with Gradle 2.6
 *
 * @author philipp, @date 27.04.16 20:41
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
